config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reviews/index'
  root to: "reviews#index"
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  # has_many :comments
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_one_attached :image
end

app/models/reviews_tag.rb
class ReviewsTag

  include ActiveModel::Model
  attr_accessor :title, :opus_title, :author_name, :authors_website, :text, :user_id, :tag_name, :tag_attr, :image

  with_options presence: true do
    validates :title, :text, :opus_title, :author_name
    validates :tag_name
  end

  def save
    review = Review.create(image: image, title: title, opus_title: opus_title, author_name: author_name, authors_website: authors_website, text: text, user_id: user_id)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save

    TagMap.create(review_id: review.id, tag_id: tag.id)
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :tag_name, uniqueness: true

  has_many :tag_maps
  has_many :reviews, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord

  belongs_to :review
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :reviews
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :self_introduction])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_review_tag, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.order("created_at DESC")
  end

  def new
    @review = ReviewsTag.new
  end

  def create
    @review = ReviewsTag.new(review_params)
    if @review.valid?
      @review.save
      return redirect_to root_path
    else
      render :new
    end
    # @review = Review.new(review_params)
    # if @review.save
    #   redirect_to root_path
    # else
    #   render :new
    # end
  end

  def show
  end

  def edit
    if current_user.id != @review.user.id
      redirect_to root_path
    end
  end

  def update
    @review = 
    if @review.update(review_params)
      redirect_to edit_review_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != @review.user.id
      redirect_to root_path
    end
    @review.destroy
    redirect_to root_path
  end
  
  private
  def review_params
    params.require(:reviews_tag).permit(:id, :image, :title, :opus_title, :author_name, :authors_website, :text, :tag_name).merge(user_id: current_user.id)
    # params.require(:review).permit(:image, :title, :opus_title, :author_name, :authors_website, :text).merge(user_id: current_user.id)
  end

  def review_tag_params
    params.permit(:id, :image, :title, :opus_title, :author_name, :authors_website, :text, :tag_name).merge(user_id: current_user.id)
  end

  def find_review_tag
    @review = Review.find(params[:id])
    @reviews_tag = ReviewsTag.new(@review_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareImpressions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar bg-dark navbar-dark">
      <!-- Brand -->
      <%= link_to "Share Impressions", root_path, class: "navbar-brand" %>
      <!-- Links -->
      <ul class="navbar-nav" id="nav_items">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= current_user.name %></a>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
            Menu
          </a>
          <div class="dropdown-menu">
            <% if user_signed_in? %>
              <%= link_to "投稿する", new_review_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="#">お気に入り</a>
              <a class="dropdown-item" href="#">タグ一覧</a>
              <a class="dropdown-item" href="#">作品タイトルで検索</a>
            <% else %>
              <a class="dropdown-item" href="#">タグ一覧</a>
              <a class="dropdown-item" href="#">作品タイトルで検索</a>
            <% end %>
          </div>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<% if user_signed_in? && current_user.id == review.user_id %>
  <div class="card border-0">
  <%= link_to edit_review_path(review.id) do %>
    <div class="card-contents">
      <div class="btn btn-primary my-3 w-100">
        <%= review.opus_title %>
      </div>
      <% if review.image.attached?%>
        <%= image_tag review.image %>
      <% else %>
        <%= image_tag "sample4.jpg" %>
      <% end %>
    </div>
    <div class="px-3" id="info_wrapper">
      <span id="info">
        <%= review.title %>
      </span>
      <span id="info2">
        <%= review.user.name %>
      </span>
    </div>
  <% end %>
  </div>
<% else %>
  <div class="card border-0">
  <%= link_to review_path(review.id) do %>
    <div class="card-contents">
      <div class="btn btn-primary my-3 w-100">
        <%= review.opus_title %>
      </div>
      <% if review.image.attached?%>
        <%= image_tag review.image %>
      <% else %>
        <%= image_tag "sample4.jpg" %>
      <% end %>
    </div>
    <div class="px-3" id="info_wrapper">
      <span id="info">
        <%= review.title %>
      </span>
      <span id="info2">
        <%= review.user.name %>
      </span>
    </div>
  <% end %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="container-field">
  <%= form_with model: @review, class: 'form', local: true do |f| %>
  <div class="row" id="top_part">
    <div class="col-sm-8" id="top_left">
      <div class="mx-5 my-3" id="opus_title">
        <%= f.text_field :opus_title, class: "edit-left" %>
      </div>
      <div class="card mx-5 border-0" id="card_m">
        <label for="opus_image" class="card-contents">
          <%= f.file_field :image, id:"opus_image" %>
          <div id="image_preview"></div>
          <% if @review.image.attached?%>
            <%= image_tag @review.image %>
          <% else %>
            <%= image_tag "sample4.jpg" %>
          <% end %>
        </label>
      </div>
    </div>
    <div class="col-sm-4" id="top_right">
      <div class="bg-light mt-5" id="card_s">
        <span>レビュー投稿日：<%= @review.created_at.strftime('%Y/%m/%d') %></span>
        <span>レビュワー：<%= @review.user.name %></span>
      </div>
      <div class="bg-light mt-5" id="card_s">
        <span>作品情報</span>
        <span>作者名：<%= f.text_field :author_name, class: "edit-right" %></span>
        <span>作者HP：<%= f.text_field :authors_website, class: "edit-right" %></span>
      </div>
      <div class="bg-light mt-5" id="card_s">
        <span>タグ情報</span>
        <span><%= f.collection_select(:tag_name, Tag.all, :tag_name, :tag_name, {}, {class:"edit-right"}) %></span>
      </div>
    </div>
  </div>
  <div class="row" id="lower_part">
    <div class="col-sm-8 border-0" id="lower_left">
      <div class="form-group mx-3 my-4" id="input_lower">
        <h5>レビュータイトル</h5>
        <%= f.text_field :title, class: "edit-title" %>
      </div>
      <div class="form-group mx-3 my-4" id="input_lower">
        <h5>レビュー</h5>
        <%= f.text_area :text, class: "edit-text" %>
      </div>
      <div id="edit_btn">
        <div class="btn_guide mr-3">レビュー内容を修正した場合はこちら</div>
        <div class="form-group  mr-3" id="submit_btn">
          <%= f.submit '編集を完了する', class: "btn btn-secondary", style: "width: 180px" %>
        </div>
      </div>
      <div id="delete_btn">
        <div class="btn_guide mr-3">レビューを削除する場合はこちら</div>
        <div class="form-group  mr-3" id="submit_btn">
          <%= link_to 'レビューを削除', review_path(@review.id), method: :delete, class: "btn btn-secondary", style: "width: 180px" %>
        </div>
      </div>
    </div>
    <div class="col-sm-4" id="lower_right">
    </div>
  </div>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8" >
      <div class="m-2" >
        <%= render partial: 'review', collection: @reviews %>
      </div>
    </div>
    <div class="col-sm-4" style="background: lightblue;">
      ComingSoon!
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container-field">
  <%= form_with model: @review, url: reviews_path, class: 'form', local: true do |f| %>
    <div class="row" id="top_part">
      <div class="card col-sm-5 border-0" id="top_left">
        <label for="opus_image" class="card-contents" id="image_field">
          <%= f.file_field :image, id:"opus_image" %>
          <div id="image_preview"></div>
          <%= image_tag "sample4.jpg", id: "sample_image" %>
          <div id="title_setting">
            <p class="card-title" id="image_title">タイトルイメージ（クリックして添付してください）</p>
          </div>
        </label>
      </div>
      <div class="col-sm-7" id="top_right">
        <div class="form-group" id="input_top">
          <h6>ゲームタイトル / ver</h6>
          <%= f.text_field :opus_title, class: "form-control" %>
        </div>
        <div class="form-group" id="input_top">
          <h6>作者</h6>
          <%= f.text_field :author_name, class: "form-control" %>
        </div>
        <div class="form-group" id="input_top">
          <h6>作者HP</h6>
          <%= f.text_field :authors_website, class: "form-control" %>
        </div>
        <div class="form-group" id="input_top2">
          <h6>タグ</h6>
          <%= f.collection_select(:tag_name, Tag.all, :tag_name, :tag_name, {}, {class:"form-control", id:"tag-select"}) %>
          <%# <%= f.text_field :tag_name, class: "form-control" %>
        </div>
      </div>
    </div>
    <div id="lower_part">
      <div class="form-group mx-3 my-4" id="input_lower">
        <h5>レビュータイトル</h5>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group mx-3 my-4" id="input_lower">
        <h5>レビュー</h5>
        <%= f.text_area :text, class: "form-control", style: "height: 32vh" %>
      </div>
      <div class="form-group  mr-5" id="submit_btn">
        <%= f.submit '投稿する', class: "btn btn-primary", style: "width: 160px" %>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="container-field">
  <div class="row" id="top_part">
    <div class="col-sm-8 border-0" id="top_left">
      <div class="mx-5 my-3" id="opus_title">
        <%= @review.opus_title %>
      </div>
      <div class="card mx-5" id="card_m">
        <div class="card-contents">
          <% if @review.image.attached?%>
            <%= image_tag @review.image %>
          <% else %>
            <%= image_tag "sample4.jpg" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-4" id="top_right">
      <div class="bg-light mt-5" id="card_s">
        <span>レビュー投稿日：<%= @review.created_at.strftime('%Y/%m/%d') %></span>
        <span>レビュワー：<%= @review.user.name %></span>
      </div>
      <div class="bg-light mt-5" id="card_s">
        <span>作品情報</span>
        <span>作者名：<%= @review.author_name %></span>
        <span>作者HP：<%= @review.authors_website %></span>
      </div>
    </div>
  </div>
  <div id="lower_part">
    <div class="form-group mx-3 my-4" id="input_lower">
      <h5>レビュータイトル</h5>
      <%= @review.title %>
    </div>
    <div class="form-group mx-3 my-4" id="input_lower">
      <h5>レビュー</h5>
      <%= @review.text %>
    </div>
  </div>
</div>